### PR TITLE
DBZ-6873 Upgrade to MySQL 8.2

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-6873

### CODE REVIEW

**Comment by jpechane** [comment]
Waiting for PRs for CI and Debezium pom before merge. Otherwise LGTM.

**Comment by ani-sha** [comment]
@jpechane re debezium pom, I don't see `8.1` tag for the [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags) image, then how can we enable in CI?

**Comment by jpechane** [comment]
Please see `version.mysql.server` property

**Comment by ani-sha** [comment]
@jpechane I mean about that only. 
```
[ERROR] DOCKER> Unable to pull 'mysql/mysql-server:8.1' : {"message":"manifest for mysql/mysql-server:8.1 not found: manifest unknown: manifest unknown"} (Not Found: 404) [{"message":"manifest for mysql/mysql-server:8.1 not found: manifest unknown: manifest unknown"} (Not Found: 404)]
```

**Comment by jpechane** [comment]
ok I just checked https://hub.docker.com/r/mysql/mysql-server/tags and there is no activity for 9 months
But https://github.com/mysql/mysql-docker/tree/main/mysql-server is kept updated. We need to find out if the images are published elsewhere and decide the next steps.

Should we switch to different Docker Images, should we build our own etc.

**Comment by mfvitale** [comment]
Should we use this one https://hub.docker.com/_/mysql/tags instead?

**Comment by jpechane** [comment]
Well, the other one is from Oracle which can be considered officil one too. I'd rather first get it back online using the images we are using since the project start. Switching to a different source of images is something we can consider separately.

**Comment by jpechane** [comment]
@ani-sha Could you please prepare 8.1 PR in main repo? Given the latest changes I think we'll be able to finish the task. Thanks

**Pull request merged**
