### PR TITLE
DBZ-5448 Add PostgreSQL 15 container

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-5448

### CODE REVIEW

**Comment by Naros** [comment]
Not only do we require https://github.com/debezium/postgres-decoderbufs/pull/29 but we also require https://github.com/eulerto/wal2json/pull/247 for the `wal2json` code to compile.  In addition, we need to wait for the postgis components to be made available for Postgres15, so at this point this is somewhat stalled.

**Comment by gunnarmorling** [comment]
The wal2json PR has been merged. Though we may not need it anyways, assuming support for it is still planned to be removed for DBZ 2.0?

**Comment by jpechane** [comment]
Good point, at the time of release Debezium 2.0 will be the stable branche so we can drop wal2json support.

**Comment by jpechane** [comment]
Incorporated in https://github.com/debezium/container-images/pull/307

**Pull request closed without merging**
